version: '3'
services:
  cockroachdb:
    image: cockroachdb/cockroach:v23.1.20
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - data:/cockroach/cockroach-data

  nakama:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        sleep 10 &&
        /nakama/nakama migrate up --database.address root@cockroachdb:26257 &&
        exec /nakama/nakama --config /nakama/data/local.yml --database.address root@cockroachdb:26257
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    depends_on:
      - cockroachdb


volumes:
  data:
